import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/navbar'
import Footer from '@/components/footer/Footer'
import Home from './page'
import { ThemeProvider } from '@/context/ThemeContext'
import Authprovider from '@/components/AuthProvider/Authprovider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
      <Authprovider>

      <div className="container">

       <Navbar />
      {children}
       <Footer />
      </div>
      </Authprovider>
      </ThemeProvider>
      
      </body>
    </html>
  )
}
